### ISSUE TITLE
Module should have option to manage DOCKER_HOST environment variable

### ISSUE THREAD

**Issue by mlehner616** [garethr/garethr-docker#103]
When specifying a tcp_bind, in order for this to actually be usable the DOCKER_HOST environment variable needs to be populated with the tcp_bind value:

Proposed solution:
```
if $tcp_bind {
  file { '/etc/profile.d/docker-host.sh': 
    ensure  => file,
    content => "export DOCKER_HOST=${tcp_bind}"
  }
}
```

**Comment by garethr** [comment]
As of #171 you can now pass an array of shell values to the module, which should support this usecase.
