### ISSUE TITLE
[Feature Request] Support authenticating with private registries

### ISSUE THREAD

**Issue by benlangfeld** [garethr/garethr-docker#113]
Similar to the [equivalent from the Chef cookbook](https://github.com/bflad/chef-docker#docker_registry).

**Comment by ChrisCrewdson** [comment]
+1 - I'll see what I can do about making this happen... Will make a pull request.

**Comment by tomstockton** [comment]
+1 - Yes please!

**Comment by caylorme** [comment]
+1

**Comment by garethr** [comment]
A PR for this exists at https://github.com/garethr/garethr-docker/pull/213 if anyone would like to try it out and feedback.

**Comment by garethr** [comment]
Good news. This has been merged and is currently in master.
