### ISSUE TITLE
[Feature Request] docker::stop  / docker::rm

### ISSUE THREAD

**Issue by farion** [garethr/garethr-docker#130]
It should be possible to stop and remove containers somehow Basically the opposite of docker::run. Otherwise it is not possible to get rid of containers you don't need anymore. 

Perhaps something like this:

// Will stop all containers with that image (and tag)
docker::stop { 'helloworld':
  image   => 'base:tag'
}

// Will remove all containers with that image (and tag)
docker::remove { 'helloworld':
  image   => 'base:tag'
}

**Comment by MichaelMackus** [comment]
:+1:

**Comment by garethr** [comment]
As of https://github.com/garethr/garethr-docker/pull/403 the module now supports making containers absent. Thanks for the report, and apologies it took a while to add the capability.
