### ISSUE TITLE
Consider shipping a changelog with each release

### ISSUE THREAD

**Issue by ryanycoleman** [garethr/garethr-docker#133]
A well written changelog gives users another tool to identify the impact of an upgrade. Consider shipping one that picks out important commits, as a minimum.

**Comment by pazoozooCH** [comment]
+1

**Comment by foxsy** [comment]
+1

**Comment by garethr** [comment]
Oh, go on then :)

Added in https://github.com/garethr/garethr-docker/blob/master/CHANGELOG.md
