### ISSUE TITLE
Consider more comprehensive documentation

### ISSUE THREAD

**Issue by ryanycoleman** [garethr/garethr-docker#135]
Example usage for the docker module is awesome but the README could be improved with a resources and class parameter reference. See the README template from Puppet Labs for an example: https://docs.puppetlabs.com/puppet/latest/reference/modules_documentation.html

**Comment by marji** [comment]
+1

**Comment by garethr** [comment]
I've published documentation using Puppet Strings at https://garethr.github.io/garethr-docker and linked that from the README. The README also now contains links to full examples demonstrating the module. The dependencies are listed in the metadata.json file for those not using the Forge.

I'd rather not duplicate either type documentation or dependencies in the README as they then need to be kept in sync. The Puppet Strings API docs are autogenerated from the code.
