### ISSUE TITLE
Adding $stuff to /etc/sysconfig/docker

### ISSUE THREAD

**Issue by tfhartmann** [garethr/garethr-docker#165]
Hi @garethr I'm looking to add ulimit entries to the sysconfig/docker config file, would you be open to a PR that allows you to add an array of arbitrary values to the end of the config file? Something like 

shell_values = [ 'foo1', 'foo2, 'foo3 -argument' ]

which show up at the end of the file as 

...
foo1
foo2
foo3 -argument

At the end of the day, I'm trying to add ulimit entries to the docker config, and it *seems* like this is the best place...

**Comment by garethr** [comment]
Thanks, #171 has been merged
