### ISSUE TITLE
new storage_driver options

### ISSUE THREAD

**Issue by cristi1979** [garethr/garethr-docker#175]
Hello, I was wandering if some new options regarding storage drivers will be accepted. I can make a new pull request for this.

Something like this: 

    # [*storage_driver*]
    #   Specify a storage driver to use
    #   Default is undef: let docker choose the correct one
    #
valid values: aufs devicemapper (or specific: loop-lvm, direct-lvm) btrfs overlayfs vfs

The storage options are currently only for device mapper driver. So I'm thinking about 2 possibilities:

    # [*storage_opt*]
    #   Specify storage driver options as an array
    #   Default is empty: use default options

or one parameter for each option

    # [*dm_basesize*]
    # [*dm_fs*]
    # [*dm_mkfsarg*]
    # [*dm_mountopt*]
    # [*dm_blocksize*]
    # [*dm_loopdatasize*]
    # [*dm_loopmetadatasize*]
    # [*dm_datadev*]
    # [*dm_metadatadev*]

I think the second option is more clear on what is expected, but more verbose.

**Comment by garethr** [comment]
Hi @cristi1979. The module does already have basic support for switching the driver, see https://github.com/garethr/garethr-docker/blob/master/manifests/init.pp#L114.

However the validation you propose, and the additional device mapper options, would both be happily accepted.

I agree the slightly more verbose options are probably the way to go.

Thanks, and any questions just let me know.

**Comment by cristi1979** [comment]
The docker package for el6 and el7 installs a file for storage options: /etc/sysconfig/docker-storage

I'm not sure if this is the case for other distributions.

For el6,el7 I will add the storage options there and for other OS's to their respective configuration files:
etc/default/docker.erb (Debian)
etc/conf.d/docker.erb (Archlinux)

**Comment by cristi1979** [comment]
I'm having some problems with those 2 validations:

  validate_re($storage_driver, '^(aufs|devicemapper|btrfs|overlay|vfs)$', 'Valid values for storage_driver are aufs, devicemapper, btrfs, overlayfs, vfs.')
  validate_re($dm_fs, '^(ext4|xfs)$', 'Only ext4 and xfs are supported currently for dm_fs.')

Travis doesn't like something here and it blows up. Do you have any experience with that?

Aside from this, I nee to make 1 more push for travis to be green again.
