### ISSUE TITLE
Define docker::exec{} 

### ISSUE THREAD

**Issue by aries1980** [garethr/garethr-docker#178]
At the moment it is not possible to execute a command inside a container. It would be nice if we could run "docker exec" in a validated way.

(I am about to submit a patch to this issue.)

**Comment by garethr** [comment]
I'd be interested in use cases for this. What specific problems do you see this solving?

**Comment by aries1980** [comment]
Once I started a container with docker::run, I'd like to execute some commands, e.g. a puppet apply.

**Comment by garethr** [comment]
I mean more specifically why? What's the actual problem you're solving by running those commands? I'm not against adding the feature, but understanding what it's would be used for (past just running the command) would be useful to understand.

**Comment by aries1980** [comment]
It simply gives a wrapper for that command. Eg. Having something like
 `docker::exec { 'db1_provisioning':
    detached => true,
    container => "${db1_container_name}",
    command => "/vagrant/infrastructure/bin/apply_puppet.sh -p ${puppet_base} -e ${environment} -x devserver_mysql_server",
}`
looks more structured to me than a plain exec beggining with docker exec.

**Comment by garethr** [comment]
Ah, I see, you're using it to trigger a puppet run on the container at the same time as the host. Thanks, I'll take a look at the PR when I get a moment.

**Comment by garethr** [comment]
Thanks to @aries1980 for the PR which adds this feature https://github.com/garethr/garethr-docker/pull/179
