### ISSUE TITLE
Image name collision

### ISSUE THREAD

**Issue by smo921** [garethr/garethr-docker#184]
Images with similar names are not getting pulled down correctly due to the way the following grep/awk pipe is written.  I'll get a PR opened for this but wanted to document it in the mean time.  Basically the grep for the image name needs a $ to terminate the regex correctly.

https://github.com/garethr/garethr-docker/blob/master/manifests/image.pp#L59
https://github.com/garethr/garethr-docker/blob/master/manifests/image.pp#L63

**Comment by garethr** [comment]
Thanks for mentioning this, note that it should be fixed in master as part of https://github.com/garethr/garethr-docker/commit/4e213a725bca9c8b6d750ba563a90c71d97f0d63
