### ISSUE TITLE
please support docker compose

### ISSUE THREAD

**Issue by levilovelock** [garethr/garethr-docker#191]
http://docs.docker.com/compose/install/

**Comment by garethr** [comment]
@levilovelock this is definitely on the cards when I get a moment. I've got a bunch of the work done already. I'll update here when I push something.

**Comment by radiumx3** [comment]
:+1:   was looking for this as well

**Comment by garethr** [comment]
Some work on this is happening in https://github.com/garethr/garethr-docker/pull/254 for those interested.

**Comment by garethr** [comment]
Compose support is now in master. Check the README for more details.
