### ISSUE TITLE
Doesn't support Debian 8 (Jessie)

### ISSUE THREAD

**Issue by 3h4x** [garethr/garethr-docker#195]
docker:~☠ /etc/init.d/container start
[....] Starting docker-container (via systemctl): docker-container.serviceFailed to start docker-container.service: Unit docker-container.service failed to load: No such file or directory.

**Comment by garethr** [comment]
Hi @3h4x. Could you provide more details about how you created this and what platform you're running?

**Comment by 3h4x** [comment]
@garethr  
yes, sorry for not including it in the first place.
The problem occurs on debian jessie, it creates normal init.d file which won't run on systemd. I tried that once and had to create systemd .service myself and enable it.
I might dive deeper into that problem because of so many pros of docker ;)

**Comment by garethr** [comment]
Ah, the module probably won't work out-of-the-box on Jessie yet. Post https://github.com/garethr/garethr-docker/pull/200 it should work on Debian 7 is those settings, I need to move those into params at some point.

The module does have systemd configs, but doesn't default to them which is what you've run into. It should be relatively simple to make those changes though, if you have time.

**Comment by 3h4x** [comment]
I'll look into it in my spare time

**Comment by garethr** [comment]
Looks like we have some work on this in https://github.com/garethr/garethr-docker/pull/210

**Comment by RenoFR** [comment]
Hi

It's work fine on jessie
can you just add support for systemd ?
On Jessie you must modify the /lib/systemd/system/docker.service file instead of /etc/default/docker for launch options

Thx

**Comment by Debilski** [comment]
Shouldn’t this rather use the package from jessie-backports rather than `wget -qO- https://get.docker.com/`?

**Comment by garethr** [comment]
Full Debian support is coming in a version 5 of the module. This work is just about complete in #311.

**Comment by RenoFR** [comment]
Great !!


Thanks !
