### ISSUE TITLE
iptables, icc bip flags

### ISSUE THREAD

**Issue by sbpaul** [garethr/garethr-docker#196]
Hi,

Just short: please add iptables, icc and bip flags to the manifests and templates.

best,
Dennis

**Comment by garethr** [comment]
Hi @sbpaul. Could you expand on this request a little? Describing exactly what you're trying to do would be useful. How you see the Puppet DSL supporting that would be ideal. Thanks

**Comment by sbpaul** [comment]
Hi Garethr,

okay there a parameters like deactivating automatic iptable rules.
I need to have those in puppet, too. i currently patch the config template for adding the --iptables=false and the --bip parameter for changing the network which docker use internally.

**Comment by thijsterlouw** [comment]
+1 from me. I need --bip as well. See:
https://docs.docker.com/articles/networking/#docker0

 ``--bip=CIDR — supply a specific IP address and netmask for the docker0 bridge, using standard CIDR notation like 192.168.1.5/24.``

**Comment by pimpimpim** [comment]
Another +1 from me.

**Comment by garethr** [comment]
This should now be supported in master, thanks to #471 and friends
