### ISSUE TITLE
docker::run should support ensure => absent

### ISSUE THREAD

**Issue by rtyler** [garethr/garethr-docker#218]
Related to #130 

For my use-case I'm not necessarily interested in removing the container from the host but rather just stopping the running of it via upstart/systemd/whatever

**Comment by inhumantsar** [comment]
+1  it took me a minute to realise that systemd was restarting containers i had `docker rm -f`'d

**Comment by ziporah** [comment]
I added this request #291 if you now set runnnig=false in your config, it will make sure the docker service is disabled but the configuration will stay in place and the container can manually be started if required.

**Comment by prosegay** [comment]
In my config, certain hosts don't have docker installed however with ensure=>absent I get (v4.1.1):
Error: Could not enable docker: Execution of '/sbin/chkconfig --add docker' returned 1: error reading information on service docker: No such file or directory
Error: /Stage[main]/Docker::Service/Service[docker]/enable: change from false to true failed: Could not enable docker: Execution of '/sbin/chkconfig --add docker' returned 1: error reading information on service docker: No such file or directory

**Comment by garethr** [comment]
Thanks for reporting. As of https://github.com/garethr/garethr-docker/commit/543b66fd58676164f5a6f7aab99508b440777346 the module now supports absent on run.
