### ISSUE TITLE
init.d scripts do not work on reboot

### ISSUE THREAD

**Issue by pazoozooCH** [garethr/garethr-docker#230]
There seems to be a conceptual problem with the init.d scripts (using version 3.5.0 of the module):

The start script will store a cid-file at /var/run. However, this is a temporary filesystem (at least with Ubuntu) that will be recreated at reboot. This means that the cid-files will be lost.

The start scripts now have an if-else that checks for the presence of the cid-file. On a reboot, this goes to the else-part that tries to execute docker run. This will fail with a duplicate name error if the container is named and has only been stopped, not removed (which is quite a common case imho).

The init scripts should be smart enough to check for a stopped (named) container, even if the cid-file doesn't exist.

**Comment by garethr** [comment]
@pazoozooCH the cid-file approach turned out to be quite brittle for a number of reasons and has not been replaced in the 4.x series. I'll close this issue as _I think_ it should be fixed now, but if you recreate on the latest release let me know.
