### ISSUE TITLE
No support for Ubuntu 15.04 due to systemd swap

### ISSUE THREAD

**Issue by nvcnvn** [garethr/garethr-docker#243]
On Ubuntu 15.05 they use systemd instead of Upstart for default.
I must swtich back to Upstart to run my old Puppet code.
Do you think this should be handle by the module?

**Comment by garethr** [comment]
Yes, the module should definitely support 15.05, but doesn't yet. This might be as simple as switching some logic (as the module already supports systemd for other distros). I'll update this issue when we have that support, or if you have time and inclination I'll happily review a PR.

**Comment by garethr** [comment]
Just to note that this is now just about working in #311.
