### ISSUE TITLE
repo_opt doesnt work when using cloned channels on RedHat

### ISSUE THREAD

**Issue by lvlie** [garethr/garethr-docker#248]
Hi,

The new repo_opt option in params.pp should be overidable, since it breaks installation on RedHat based distributions with differently named channels (e.g. when using a satellite server with cloned channels). 

      # repo_opt to specify install_options for docker package
      if (versioncmp($::operatingsystemmajrelease, '7') == 0) {
        if $::operatingsystem == 'RedHat' {
          $repo_opt = '--enablerepo=rhel7-extras'

In our own mirror we commented out the specific lines, I'll try to write something nicer and create a pull request if I have the time. In the meantime I thought this issue was in order. 

Thanks,
Leon

**Comment by lvlie** [comment]
@jonnytpuppet I was wondering about the rationale behind your PR's. Is the extra's channel disabled by default? In that case I understand but still setting the repo_opt should really be optional because it will break a lot of installations.

**Comment by sjoeboo** [comment]
+1, this is breaking new Rhel7 installs. cloned channel is:

 rhel-x86_64-server-extras-7

**Comment by garethr** [comment]
Just a note that this should be fixed in https://github.com/garethr/garethr-docker/pull/258.

Thanks for reporting everyone.

**Comment by lvlie** [comment]
Thanks @coreone and @garethr , this extra overridable variable is indeed a quite simple solution. Although opt-in would be cleaner, I can live with this solution :)
