### ISSUE TITLE
module is failing when using it in an environment that does not allow access to external access to EPEL.

### ISSUE THREAD

**Issue by ed-mt** [garethr/garethr-docker#249]
in a particular use case which i've had to use it in, EPEL access is not allowed externally and must use internal mirrors instead. The module needs to be modified, to manage EPEL (as it's doing at the moment), however allow it to be overridden in cases like this.

**Comment by garethr** [comment]
Thanks for reporting the issue, I've merged the referenced PR to master to make this configurable. Thanks again
