### ISSUE TITLE
Support for private repos hosted on Docker Hub

### ISSUE THREAD

**Issue by nvalentine-puppetlabs** [garethr/garethr-docker#275]
Large Search Engine(TM) Container Registry team would like to be able to pull images from private repos via credentials in 'dockercfg' and/or authconfig.

@mattmoor

**Comment by garethr** [comment]
I'm presuming that you've seen the new private registry support? https://github.com/garethr/garethr-docker#private-registries But don't want the credentials in the manifest/catalogue? Or something else?

**Comment by mattmoor** [comment]
I hadn't thanks!

**Comment by garethr** [comment]
@mattmoor ah, thanks. I'll close this and assume that works for you :) If not then please do open an issue. Note that this is currently only in master. It should be available in a release of garethr-docker soon, and then in the puppetlabs supported module a little after that.

**Comment by david-caldwell** [comment]
This refers to private registries, but does not seem to be working for private repos hosted on dockerhub.com
