### ISSUE TITLE
docker::run { restart => anything } should use title for container name

### ISSUE THREAD

**Issue by jstangroome** [garethr/garethr-docker#286]
If any value is specified for the `restart` parameter of the `docker::run` class then the sanitised title is used for the CID file but it should also be used as the container name, potentially based on whether the `use_name` parameter has also been set.

**Comment by garethr** [comment]
I think this is now fixed. If you still see the problem let me know and I'll delve in. `use_name` is no-longer required which simplifies some of the usage here.
