### ISSUE TITLE
Puppet never returns

### ISSUE THREAD

**Issue by mleone896** [garethr/garethr-docker#293]
So the module seems to work great. The problem I"m seeing is that when running puppet on a node that is gong to configure docker containers it never returns I have to ctrl-c and everything looks like it was setup right. This may be something I'm doing wrong but some guidance / assistance would be awesome. Thanks in advance for your help. !

**Comment by garethr** [comment]
Could you provide more details about how you are running puppet? And maybe the manifest you are running? Any commands you are running or output from those commands might be useful.

**Comment by mleone896** [comment]
@garethr thanks for your quick reply.. This can be resolved, it was a config issue on my end .. Thanks so much again .!!
