### ISSUE TITLE
docker::run ignores 'depends'

### ISSUE THREAD

**Issue by onibox** [garethr/garethr-docker#295]
It looks like the 'depends' variable is currently not used in docker::run.
Or am i missing something?

**Comment by garethr** [comment]
You are correct. It looks like the implementation of this has been broken with the move to the `docker_run_flags` function.

**Comment by lorijean44** [comment]
I do see the depends variable used in the systemd templates.

**Comment by garethr** [comment]
I think this should be fixed now, potentially before but definitely in https://github.com/garethr/garethr-docker/pull/393/files which is now in master. If not let me know and I'll investigate further. And thanks for reporting the issue.
