### ISSUE TITLE
Provide a flag to disable docker::run services

### ISSUE THREAD

**Issue by skython** [garethr/garethr-docker#309]
Docker container dependencies are not considered by the init system.
This behavior leads to errors when starting containers where the links to other containers cannot be fulfilled.

It would be nice if there would be a way to disable these services and let puppet start these services in the right order. Currently the **enable** property is always **true** for all docker::run services.

    service { "docker-${sanitised_title}":
      ensure    => $running,
      enable    => true,
      hasstatus => $hasstatus,
      require   => File[$initscript],
    }

**Comment by garethr** [comment]
Would a better way to solve this specific problem be to pass the link information to the init system in this case?

I'd also be open to a PR to expose enable to the `docker::run` interface.

**Comment by nuttycom** [comment]
Something else that is needed along these lines is a mechanism to clean up the initscripts when they are no longer relevant. ensure => absent should remove the initscript, and docker rm -f the container.

**Comment by zkisling** [comment]
+1

**Comment by c0deaddict** [comment]
+1

**Comment by coolacid** [comment]
Happy to find this is already a request. +1

**Comment by garethr** [comment]
Good news to much of this description. All in master:

* You can now pass absent to run, which removes the init scripts and as well as the containers (as mentioned by @nuttycom )
* depends is now a touch more powerful, and should address the original ordering issue: https://github.com/garethr/garethr-docker/commit/c316c28686afb3909e9076c307dd434f25b21a1f
* and if you'd rather simply reply on docker's built-in process supervision you can pass a restart option and avoid the init scripts altogether

Hopefully in combination that address the issues, but if not feel free to open a new one with more details. Thanks all.
