### ISSUE TITLE
Support new apt and yum repos

### ISSUE THREAD

**Issue by zxjinn** [garethr/garethr-docker#310]
First of all, thanks Gareth for making such a great Docker module. I've just started using it and it's so feature rich and just generally outstanding! I really appreciate all the work you put into this and your other modules.

Docker [blogged](http://blog.docker.com/2015/07/new-apt-and-yum-repos/) a few days ago saying they are no longer going to be updating the old repositories (located at get.docker.com) with newer versions of Docker. Presumably, this means that anything newer than 1.7.0 will not be available in those old repositories.

This means the /etc/apt/sources.list.d/docker.list file would need to change from
```
deb https://get.docker.io/ubuntu docker main
```
to something like
```
deb https://apt.dockerproject.org/repo ubuntu-${::lsbdistcodename} main
```

I was thinking it would be an init.pp flag, something like a `use_dockerproject_repo` bool with the default set to false as to not break existing functionality.

It appears as if RHEL platforms use epel to get Docker, in this updated repo that might no longer be necessary (?) but I can not be sure as I don't generally use yum-based systems for Docker stuff.

This is somewhat related to #281, since the package name changes on all Debian and RHEL platforms to `docker-engine`.

**Comment by garethr** [comment]
The module already supports `use_upstream_package_source` for this purpose. I'm working on  https://github.com/garethr/garethr-docker/tree/new-docker-repos which should resolve this.

**Comment by zxjinn** [comment]
Great! I like that direction, it's much cleaner than my suggestion of adding yet another bool. I would just suggest adding some docs to the README to help people understand how to add the new repos. Thanks!

**Comment by sjoeboo** [comment]
+1 this looks good (just started playing with this branch, so far so good)

**Comment by sjoeboo** [comment]
Actually, would it be reasonable to ask that removing/replacing existing docker packages with the official docker-engine ones be included/in-scope? On an example RHEL-7 system w/ docker install docker-engine (rightfully) conflicts. Maybe have some package {'$legacy_name': ensure => absent} as a requires for the docker-engine install ?

**Comment by garethr** [comment]
@sjoeboo I'd thought a little about that, and asked on puppet-dev for any opinions. The problem with doing that is that it's not what everyone will want. The previous default uses official packages, just official packages from RedHat rather than Docker.

My view for one-off things like this is they are probably better noisy and left for the end user to decide the best cause of action.

**Comment by sjoeboo** [comment]
fair enough, once this is merged its simple enough to wrap it in something to remove the conflicting packages first.
