### ISSUE TITLE
Ubuntu systemd version has problems with bind parameters

### ISSUE THREAD

**Issue by hkroger** [garethr/garethr-docker#312]
Basically when you have things like this set up:
docker::tcp_bind: tcp://0.0.0.0:2375
docker::socket_bind: unix:///var/run/docker.sock

Ubuntu 15.04 has hardcoded settings in /lib/systemd/system/docker.service
   
    ...
    ExecStart=/usr/bin/docker -d -H fd://
    ...

So, obviously new bind parameters won't go through...

**Comment by garethr** [comment]
I'm currently working on adding support for the new docker repositories in https://github.com/garethr/garethr-docker/pull/311 and have a resolution for that issue there.

Once that's resolved I'm hoping to add explicit support for 15.04 to the module.

**Comment by garethr** [comment]
I've verified this is fixed in #311 by ensuring the acceptance tests pass which cover this case: https://github.com/garethr/garethr-docker/blob/master/spec/acceptance/docker_full_spec.rb#L43

The solution is adding an override file which provides a more complete ExecStart

**Comment by PierreR** [comment]
Is this fixed in `4.1.1` ? I have the same problem but with CentOS 7.

**Comment by garethr** [comment]
@PierreR no, it will be fixed in 5 when I finally get time to ship it. FOr the moment see the branch in #311
