### ISSUE TITLE
How can i use the module?

### ISSUE THREAD

**Issue by hacpai** [garethr/garethr-docker#316]
Hello, it's the first time use puppet. Could you give me some suggestion?

puppet's version is 4.2.1.

In cat /etc/puppetlabs/code/environments/production/manifests/site.pp

```
include 'docker-test'
```

In cat /etc/puppetlabs/code/environments/production/modules/docker-test/manifests/init.pp

```puppet
class 'docker-test' {

  include 'docker'

  ::docker::image { 'ubuntu':
    ensure    => 'absent',
    image_tag => 'precise',
 }

  ::docker::run { 'helloworld':
    image => 'ubuntu',
    command => '/bin/echo "Hello world"',
  }
}
```

**Comment by garethr** [comment]
Hi @JohnHwee are you seeing a particular error with the above?

From just reading the code:

1. You're ensuring `absent` on the image, and then trying to use it
2. The command you're running in the container will exit, so the service will exit too

**Comment by JohnHwee** [comment]
@garethr 
I think the syntax error.
```
[root@consul-test-02 tmp]# puppet agent -t
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Error while evaluating a Function Call, Could not find class ::docker-test for consul-test-02 at /etc/puppetlabs/code/environments/production/manifests/site.pp:1:1 on node consul-test-02
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```

**Comment by garethr** [comment]
@JohnHwee from the error I'm not sure this is a problem with the module but something else with your puppet setup.

It might be worth renaming your module to `docker_test`. From the documentation (and some far off memories) I don't think hyphens are valid in module names: https://docs.puppetlabs.com/puppet/latest/reference/lang_reserved.html#modules

**Comment by JohnHwee** [comment]
@garethr Thank you for help. I rename `docker-test` to `docker_test`, It prompt syntax error.

```puppet
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Syntax error at 'docker_test' at /etc/puppetlabs/code/environments/production/modules/docker_test/manifests/init.pp:1:7 on node consul-test-02
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```
But I don't understand what error is.

In init.pp
```puppet
class 'docker_test' {

  include 'docker'

  ::docker::image { 'ubuntu':
    ensure    => 'absent',
    image_tag => 'precise',
 }

  ::docker::run { 'helloworld':
    image => 'ubuntu',
    command => '/bin/echo "Hello world"',
  }
}
```

**Comment by garethr** [comment]
I would recomment trying out tools like [puppet-syntax](https://github.com/gds-operations/puppet-syntax) and [puppet-lint](http://puppet-lint.com/).

You could also try and remove everything from the class in question and see if you can get the error to go away. This does appear to be a higher level issue that the module based on the error

**Comment by garethr** [comment]
Closing as not heard anything in a while, and I think the best support if probably the puppet-user IRC or mailing list for the broader issue.
