### ISSUE TITLE
Feature: option to manage a cron which removes dangling images

### ISSUE THREAD

**Issue by alexpdp7** [garethr/garethr-docker#320]
We've been using this Puppet module to deploy a Docker lab. However, we've found out that we accumulate dangling images and we need to clean it up regularly.

It would be nice if the module let you create a cron file which does:

  $ docker rmi $(docker images --quiet --filter "dangling=true")

daily, or something like that.

**Comment by garethr** [comment]
I\d recommend something like https://github.com/spotify/docker-gc for this purpose. You could certainly write a defined type around creating a cron for this but I think that's probabl outside the scope of this module at the moment (although if someone submitted a compelling PR I might be convinced to change my mind).
