### ISSUE TITLE
Log files included in 4.1.0 release

### ISSUE THREAD

**Issue by nuttycom** [garethr/garethr-docker#323]
It looks like a number of log files that should be .gitignore'd (in modules/docker/log) have been inadvertently included in the released version.

**Comment by garethr** [comment]
thanks for the heads up. I'll look to release a 4.1.1 with these removed. Being included in .gitignore isn't enough I don't think for puppet module tool to ignore them.

**Comment by garethr** [comment]
I've released a 4.1.1 to the Forge. Thanks for the heads up.
