### ISSUE TITLE
All CentOS 6.x versions should be supported 

### ISSUE THREAD

**Issue by rpocase** [garethr/garethr-docker#326]
With the new official docker package repositories, CentOS 6.x it should be trivial to absorb support for, unless there are system differences I'm not aware of.

**Comment by garethr** [comment]
The module should already support Centos 6.6 (https://github.com/garethr/garethr-docker/blob/master/metadata.json#L20). The issue there is making sure you have an up-to-date kernel.

**Comment by rpocase** [comment]
I was looking at the portion that handles $docker::use_upstream_package_source for RHEL operating systems (https://github.com/garethr/garethr-docker/blob/master/manifests/install.pp#L68). It seems like this is the wrong place to fail out. This is the only place I could find that restricted 6.x support based on the minor release number. There is still a lot of value in managing the installation and configuration of docker, even if the kernel isn't managed.
