### ISSUE TITLE
Using a collector that matches no resources can break chained ordering

### ISSUE THREAD

**Issue by dominics** [garethr/garethr-docker#329]
At https://github.com/garethr/garethr-docker/blob/master/manifests/init.pp#L231, we use a chained ordering statement, with resource collectors:

```puppet
Class['docker'] -> Docker::Registry <||> -> Docker::Run <||>
```

However, the language reference warns that this "chain can be broken if it includes a collector whose search expression doesn’t match any resources". See https://docs.puppetlabs.com/puppet/latest/reference/lang_relationships.html#potential-for-breaking-chains - in this case, that'd be where someone was using one or more `docker::run` resources, with no `docker::registry` resources.

**Comment by garethr** [comment]
@dominicbecker thanks. This is now fixed in master, in what is admittedly a bit of a brute force manner. https://github.com/garethr/garethr-docker/blob/8d7a21603eaa9e1b6e593e5382c71e2ecb00f70e/manifests/init.pp#L391-L393
