### ISSUE TITLE
Waiting for containers to come up is hard

### ISSUE THREAD

**Issue by jeffb-stell** [garethr/garethr-docker#337]
I don't know the proper way to implement this (flag to docker::run to be blocking? docker::run_completed resource?) but if you have resources that depend on a docker container actually being in a running state, it's somewhat difficult. As an example:

  # wait for 3 docker containers to be running
  exec { 'wait-for-docker-containers':
    require  => [ Docker::Run['guacd'], Docker::Run['guacamole'], Docker::Run['mysqld'] ],
    provider => 'shell',
    command  => 'while [ $(docker ps --filter "running=1" -q |  wc -l) != "3" ]; do sleep 1; done',
  }

If this pupmod could implement a cleaner solution to only start dependents after a container was actually running, I would be so happy.

**Comment by garethr** [comment]
The `depends` option should do this, with some help from `after`. Some recent improvements here too: https://github.com/garethr/garethr-docker/commit/c316c28686afb3909e9076c307dd434f25b21a1f.
