### ISSUE TITLE
Ubuntu install does not follow Docker's guide

### ISSUE THREAD

**Issue by etlweather** [garethr/garethr-docker#345]
The install of Docker on Ubuntu 14.04 does not install from the right source. 

The source per http://docs.docker.com/installation/ubuntulinux/ is https://apt.dockerproject.org/repo and the package is docker-engine - that's what the script that gets pulled from https://get.docker.com/ does.

I was expecting this module to do the same.

**Comment by garethr** [comment]
@etlweather just updating issues. Master now uses the updated repositories.
