### ISSUE TITLE
Debian Wheezy repo does not yet have docker.io package

### ISSUE THREAD

**Issue by jae2** [garethr/garethr-docker#347]
Currently the docker module will attempt to install docker using the docker.io package. Currently this is not present and this will fail:
e.g. 
```
==> apt:
==> apt: E: Package 'docker.io' has no installation candidate

```
The instructions for installing docker on Wheezy involve some slightly different [steps](https://docs.docker.com/installation/debian) which are a little more crude than running apt-get install. 

This is not necessarily a problem of the puppet module, but perhaps we should either:

a) Fail with "wheezy is not yet supported".
b) Attempt to run the docker wheezy installation steps within the manifest.

**Comment by garethr** [comment]
Debian is works but isn't supported at the moment as noted. This will change in 5.0, which you can track in #311.

I'll close this issue just to avoid duplication, but if you try out the branch in the above PR it should hopefully work out.

**Comment by jae2** [comment]
Thanks, I'll follow that PR instead..
