### ISSUE TITLE
docker::run depends array issues

### ISSUE THREAD

**Issue by jarekg83** [garethr/garethr-docker#358]
Hi,

If docker container relies on some NFS shares and you want to create a dependency for remote-fs.target you simply cannot as it takes service_prefix and appends by .service on the end so even if I set service_prefix='' it still adds .service on the end. 

I think that variable should be taken more literally than the way it's working now.

**Comment by garethr** [comment]
I think the work in https://github.com/garethr/garethr-docker/pull/393 which is now in master should support your usecase. If not let me know and I'll take a closer look. Thanks for reporting the issue.
