### ISSUE TITLE
Centos7.1 + docker-engine compatibility

### ISSUE THREAD

**Issue by flyinprogrammer** [garethr/garethr-docker#361]
Given I want to use my own repos
When I use this module
Then it should be as simple as:
use_upstream_package_source => false,

Actual:
So with the new docker-engine packages on centos they now use $other_args in /etc/init.d/docker
Which means I want:
https://github.com/garethr/garethr-docker/blob/master/manifests/service.pp#L96
To evaluate to False when I'm using the docker-engine package
But True when you're using the older 'docker' packages.

I have no problem writing the code to do this little case statement around package name. I just wasn't sure what you want?

Also:
https://github.com/garethr/garethr-docker/blob/master/manifests/service.pp#L104
Seems real bad? It would seem like coupling whose package to use with what init system to use might be a little overloaded, or have I misunderstood how this works?

Totally down for writing code and submitting a PR to get this issue closed. Just looking to know what direction you might want to go with any of this!!

**Comment by flyinprogrammer** [comment]
https://github.com/garethr/garethr-docker/blob/master/manifests/install.pp#L70
will also mess you up even if you say: use_upstream_package_source => false 

:-1:

**Comment by flyinprogrammer** [comment]
It's very likely I've been a complete idiot about this stuff to some degree :( I'm so sorry. more to come as soon as i have it.

**Comment by garethr** [comment]
@flyinprogrammer thanks for flagging these. The recent changes have made this a touch messy, more than happy to see PRs addressing these issues as you mention I think.

**Comment by Thorndike** [comment]
On a side note to RHEL7: It seems that the plugin is still writing some configuration data like extra_parameters to /etc/sysconfig/docker which is basically ignored. The new way on systemd based OS seems to be drop in files in a new directory as described in 

https://docs.docker.com/engine/admin/systemd/#custom-docker-daemon-options

**Comment by flyinprogrammer** [comment]
https://github.com/garethr/garethr-docker/pull/388

Fixed the issue of the systemd scripts being coupled with the package management.

@Thorndike if you don't like how the systemd stuff is laid down feel free to open a new issue ¯\_(ツ)_/¯
