### ISSUE TITLE
Different tags for image

### ISSUE THREAD

**Issue by artak116** [garethr/garethr-docker#364]
Is it possible to create multiple tags by one image? I want to declare one image with difference tag, but module gives  me error “Duplicate definition” . Regards

**Comment by garethr** [comment]
@artak116 could you provide an example of the syntax you're using?

If you are meaning you want to ensure multiple tags are present, but don't want the whole image, you can do something like:

```puppet
docker::image { 'ubuntu-vivid':
  name      => 'ubuntu',
  image_tag => 'vivid',
}

docker::image { 'ubuntu-trusty':
  name      => 'ubuntu',
  image_tag => 'trusty',
}

```

**Comment by artak116** [comment]
I didn't specify the name of image ( name      => 'ubuntu', ) and image resource automatically  took the docker::image name. Now its clear. Thank you very much.
