### ISSUE TITLE
Cyclic dependency caused by apt-transport-https -> Apt::Source <||>

### ISSUE THREAD

**Issue by chrismwendt** [garethr/garethr-docker#369]
When attempting to use the latest version of this Docker module, I encountered a cyclic dependency which is caused by https://github.com/garethr/garethr-docker/blob/master/manifests/repos.pp#L13

```puppet
Package['apt-transport-https'] -> Apt::Source <||>
```

Here is the formatted output of the cycle from Puppet:

```
Anchor[apt::key ----- present] => 
Apt::Key[Add key: ----- from Apt::Source foo] => 
File[foo.list] => 
Exec[apt_update] => 
Class[Apt::Update] => 
Anchor[apt::update] => 
Class[Apt] => 
Package[apt-transport-https] => 
Apt::Source[foo] => 
File[foo.list]
```

Is it absolutely necessary to force all occurrences of `Apt::Source` to depend on `Package['apt-transport-https']`? Perhaps there is a way to specify that it's only required for Docker.

I'm going to throw a bunch of ideas out here in case any of them are viable:

- `if already_has_https { do nothing } else { do this }`
- Pass `https` as a parameter to `Apt::Source` (does `Apt::Source` support this?)
- `include apt-transport-https` instead of introducing the collector syntax `<||>`
- Specify `Apt::Source['docker']` directly instead of using the collector
- Restrict the collector with a search expression inside the collector like `<| title == 'docker' |>`

/cc @kpaulisse

**Comment by kpaulisse** [comment]
I saw this as a chicken-and-egg problem. You need to install `apt-transport-https` in order that `apt-get update` will work with a file that uses https URLs. But you need to have `apt-get update` already run in order to be able to install the package.

I think this is causing a problem for us and possibly not others because we have all package installs dependent on all apt repos, which I think is a reasonable design choice. Specifically I mean that we are already using this:

`Class['apt'] -> Package<||>`

I understand why you are including this code in the docker module, but in my opinion the correct place to fix this is in the `apt` module itself... some sort of "transport packages to install" argument. In the meantime you could consider enclosing the `apt-transport-https` package logic in a conditional statement that can be overridden by a parameter, so that we can use your module even in the presence of the apt to package relationship I noted above.

**Comment by jkroepke** [comment]
```
Class['apt'] -> Package <| title != 'apt-transport-https' |>
```

is a bad workaround..

**Comment by sigmunau** [comment]
This causes puppet to try to install apt-transport-https before installing the apt-source that contains it on our setup.

**Comment by dalen** [comment]
Adding `apt-transport-https` to the list of `required_packages` on the apt::source in question and removing the ordering would fix this issue.

**Comment by jkroepke** [comment]
No, required_packages is deprecated and removed in feature versions of puppetlabs/apt

**Comment by jkroepke** [comment]
@garethr: Why we are using the https endpoint of the repository? http should be enough and would be fixed this issue..

**Comment by sigmunau** [comment]
@jkroepke maybe it's deprecated, but it's already used for other packages. Adding another package would not break anything new, and might fix this module for those of use that are affected by this issue

**Comment by garethr** [comment]
@sigmunau @jkroepke agreed, I'm more than happy to run deprecated options. Moving the entire community to the new apt interface is going to take a while.

@jkroepke I think that's probably a good idea given the complexity that using it has introduced. I'd be happy to see a PR if someone wants to remove the package and slip the param to the http URL. If not I'll try and get to it as time permits, definitely before the next release.

**Comment by sigmunau** [comment]
the required_packages parameter seems to me to be completely dysfunctional in the most recent version (2.2.1) of puppetlabs/apt. It adds and exec with refreshonly=true that don't have any subscribe parameter and nothing I can find has any notify on it.

**Comment by willaerk** [comment]
Perhaps a `$manage_package_repo` variable in the main class that defaults to true? A number of modules seem to do that already (eg. [puppet-nodejs](https://github.com/voxpupuli/puppet-nodejs/blob/master/manifests/init.pp#L5)).

That way, people experiencing the dependency cycle can add the docker repository using their own method for adding apt repositories.

**Comment by fessyfoo** [comment]
We're also getting hit by this issue.  

Any thoughts on the appropriate solution? 

we use the following resource default in our site.pp

```
Package {    requires => Exec['apt_update']  }
``

taking that out makes for a lot of other dependency ordering pain.

**Comment by fessyfoo** [comment]
this seems relevant:   https://github.com/puppetlabs/puppetlabs-apt/pull/427  

If I apply a liberal interpretation, it seems the guidance when `apt::source` initially removed the `required_packages` param was that the base debian system really should already have any packages required to configure and update apt repositories.    

with that interpretation it would seem the appropriate solution would be for this docker module to not try to install `apt-transport-https` at all. 

either that,  or doing what @willaerk suggests seems appropriate.

**Comment by fessyfoo** [comment]
note #480  is attempting to make the dep on apt-transport-https more precise,  but retains the fundamental issue.

**Comment by fessyfoo** [comment]
note https://github.com/garethr/garethr-docker/pull/436  [ [view with w=1](https://github.com/garethr/garethr-docker/pull/436/files?w=1) ] extends the `$docker::manage_package`  params to apply to debian as well.    which I think would suffice for @willaerk's suggestion.

However I still suggest that even with this option `apt-transport-https` not be managed by this puppet-module.   ie avoid the apt::source deps as an exercise for the site dealing with them.

**Comment by fessyfoo** [comment]
we've deployed @benlangfeld's branch from #482  that solution solves the problem for us.

**Comment by garethr** [comment]
This should be fixed in master with the application of https://github.com/garethr/garethr-docker/pull/482. Thanks to @benlangfeld.
