### ISSUE TITLE
Real time puppet logging of docker::image build ?

### ISSUE THREAD

**Issue by mickaelperrin** [garethr/garethr-docker#378]
Hi,

I was wondering if there is some way to ensure  a "real time" logging in puppet of Docker build output when using docker::image.

It could be useful to check how the build is running.

Thanks for your answers,

**Comment by garethr** [comment]
I'm not sure what you mean by 'real time' in this context. Could you provide some hypotheical output of what you had in mind?

**Comment by mickaelperrin** [comment]
Hmmm, sorry for not being precise enough.

I am mainly running puppet in standalone mode with the help of some BASH and SSH scripts. When the scripts are running, they are echoing the logs of puppet apply.

When I use docker::image to build a docker image on a remote host, I would love to see in "real time" the log updated as soon as a new line is outputed by the docker build command.

In the actual state, the log is only updated when the build failed.

Hope you better understood my request.

**Comment by lorijean44** [comment]
This will be a puppet limitation more than anything.   

However, I do notice that none of the puppet execs in the docker module give us the option to logoutput.   https://docs.puppetlabs.com/references/latest/type.html#exec-attribute-logoutput

I think that can still be delayed though and not "real time", but it's closer.

**Comment by garethr** [comment]
@mickaelperrin ah, got you. As @lorijean44 mentioned Puppet doesn't stream the output from execs to the CLI so this isn't something I can do from the module end. Feel free to start a discussion on IRC, or by opening an issue against Puppet itself at https://tickets.puppetlabs.com/browse/PUP/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel.
