### ISSUE TITLE
Dangling volumes after restarting systemd unit

### ISSUE THREAD

**Issue by nikhilo** [garethr/garethr-docker#380]
If I have a container running with a `use_name`, and with volume; the systemd service to restart the container doesn't remove the volume.

In case if the container mounts a volume, I think adding `-v` flag in following line will delete the volumes as part of service restart.
https://github.com/garethr/garethr-docker/blob/master/templates/etc/systemd/system/docker-run.erb#L16

The only way I could tackle this now, is to find and remove dangling volumes periodically with something like: https://github.com/chadoe/docker-cleanup-volumes

**Comment by garethr** [comment]
@nikhilo thanks, you're correct. This should be fixed in master since https://github.com/garethr/garethr-docker/commit/c361a3787bbe558ace18f78980c045760889a5d0 and should be in the next released version.
