### ISSUE TITLE
TLS

### ISSUE THREAD

**Issue by SergiuCip** [garethr/garethr-docker#390]
Hi there,

Thank you for building such great module which I found it very useful. 

However, we would like to use your module in a Production module, in order for that to happen we would like to implement some security around it such as: TLS verify. I was wondering if your module supports that and how do I implement it? 

Thank you,
Sergiu

**Comment by garethr** [comment]
A the moment the module doesn't provide hooks for the docker TLS setup, but I'd be happt to see a PR with that functionality. This seems to be the main reference for the required flags: https://docs.docker.com/engine/articles/https/

**Comment by JWGmeligMeyling** [comment]
:+1:

**Comment by luckyraul** [comment]
#468

**Comment by JWGmeligMeyling** [comment]
@luckyraul Thanks for adding the tests, and the build passes now as well. @garethr Are the unit tests sufficient or should Beaker integration tests also be added to ensure Docker indeed uses TLS now? Or will we test this manually?

**Comment by garethr** [comment]
Thanks to @luckyraul for this. I've merged #468

**Comment by JWGmeligMeyling** [comment]
Haven't had the opportunity to test this until today. Thanks for your efforts @luckyraul !
