### ISSUE TITLE
Docker failed on Centos7 using docker module 5.0.0

### ISSUE THREAD

**Issue by gitlabgis** [garethr/garethr-docker#406]
Hi ,

Environment:
OS: Centos7
Module: 5.0.0
docker= 1.8.2
Puppet 4

When Puppet upgraded my docker package from 1.8.2-7 to 1.8.2.10 a new systemd file was created to override the configuration.
 
The following options '-H fd://'  are in the template in templates/etc/systemd/system/docker.service.d/service-overrides-rhel.conf.erb
```
[Service]
EnvironmentFile=-/etc/sysconfig/docker
EnvironmentFile=-/etc/sysconfig/docker-storage
EnvironmentFile=-/etc/sysconfig/docker-network
ExecStart=
ExecStart=/usr/bin/<%= @docker_command %> -d -H fd:// $OPTIONS \
      $DOCKER_STORAGE_OPTIONS \
      $DOCKER_NETWORK_OPTIONS \
      $BLOCK_REGISTRY \
      $INSECURE_REGISTRY
```

By default docker add a default value to  -H unix:///var/run/docker.sock in:
 
/etc/sysconfig/docker
```
OPTIONS=" -H unix:///var/run/docker.sock -l /etc/sysconfig/docker"
```

So after troubleshooting I figured out that by removing the "H fd://" in the override template the systemd started sucessfully.

**Comment by piwi3910** [comment]
ok damm, this is what i have been looking for all the time, any fix for this bug already?

**Comment by garethr** [comment]
Mmm, odd. I wasn't able to recreate this using the acceptance tests. Running the following spins up a Centos7 machine and runs through installing and using the module:

```
BEAKER_set=centos-70-x64 bundle exec rake beaker
```

This does test using the latest version of docker, 1.9.x at the moment, so I wonder if this is a variance between 1.8.x and 1.9.x? I'll investigate further, but if you are able to provide recreate steps (or in a perfect word a test for the acceptance suite) that would be useful. And thanks for reporting.

**Comment by garethr** [comment]
After some spelunking, and others reporting the issue, I've applied that fix to master and it will be in the next release. Thanks again for reporting and including the details.
