### ISSUE TITLE
Change in docker run parameters not refreshed properly on CentOS/RHEL

### ISSUE THREAD

**Issue by lcarstensen** [garethr/garethr-docker#42]
The /etc/rc.d/init.d/docker-<containername> script that gets created with the docker-run.erb template on CentOS/RHEL6 doesn't do a "docker rm" - so if you change any value, during the refresh you get a puppet agent error.  The container is stopped, and can't be restarted because the name is already allocated.  A "docker rm" added to the stop function in the init script would allow that to work properly.

So, something along the lines of:

```
--- a/docker/templates/etc/init.d/docker-run.erb
+++ b/docker/templates/etc/init.d/docker-run.erb
@@ -94,6 +94,9 @@ stop() {
             echo -n $"Stopping $prog: "
             docker stop $(cat $cidfile)
             retval=$?
+            docker rm $(cat $cidfile)
+            retval2=$?
+            retval=$((retval + retval2))
             [ $retval -eq 0 ] && rm -f $lockfile $cidfile
             return $retval
         else
```

(that's the patch we're working with in our module, anyway)

**Comment by salimane** [comment]
This should have been fixed with the current version 
```puppet
stop() {
    echo -n "Stopping $prog: "
    $docker stop <%= @sanitised_title %>
    $docker rm <%= @sanitised_title %>
    return $?
}
```
Thanks
