### ISSUE TITLE
Docker import/load from .tar file

### ISSUE THREAD

**Issue by erikanderson** [garethr/garethr-docker#420]
Didn't see this in the readme/code, is there a way to import from a .tar file? 

https://docs.docker.com/engine/reference/commandline/import/

**Comment by garethr** [comment]
@erikanderson good idea. That's not currently supported but I'd definitely be happy to see a PR if you have time. Otherwise I'll try and get to it as time allows.

**Comment by erikanderson** [comment]
I will take a crack at it. Also would be good to add support for `load` command https://docs.docker.com/engine/reference/commandline/load/

**Comment by JimmyAstle** [comment]
After looking through the source the image class does exactly what this issue is for no? We have this working via a class something like this:

```
class mymodule::extract {
  include Class['docker']
  include Class['staging']

  staging::deploy { 'awesome.tar.gz':
    source => 'puppet:///modules/mymodule/folder/awesome.tar.gz',
    target => '/opt/data'
  }

  docker::image { 'awesome-image':
    require => Staging::Deploy['awesome.tar.gz'],
    docker_tar => "/opt/data/awesome-image.tar"
  }
}
```
