### ISSUE TITLE
docker::run removes container

### ISSUE THREAD

**Issue by MichaelMackus** [garethr/garethr-docker#422]
Any way this feature can be toggleable? I understand that docker containers are not meant to be persistent, but a lot of my containers are an empty base ubuntu container with puppet provisioning on top. It is very inefficient for these containers to get re-built every time they get started from docker::run, since they have to essentially get re-provisioned every reboot.

I understand I can commit these containers, and then run them without puppet, but this adds an extra step and since these containers are being purely used in a dev environment, it feels unnecessary atm.

**Comment by MichaelMackus** [comment]
Referring to this line specifically: [docker-run.erb](https://github.com/garethr/garethr-docker/blob/master/templates/etc/init.d/docker-run.erb#L80)

**Comment by garethr** [comment]
@MichaelMackus I'd be happy for this to be made optional. Also relevant at https://github.com/garethr/garethr-docker/blob/master/templates/etc/init.d/docker-run.erb#L105, as well as the systemd equivalents.

I'd probably go for `remove_container_on_start` and `remove_container_on_stop`, defaulting them to `true`. 

Let me know if that sounds like it would work for your usecase.

**Comment by hdeadman** [comment]
Those options would work for me. We are running some of our dev tools (gitlab, nexus) as containers and the data is in volumes created with docker volume and those named volumes got deleted when we ran the latest version of this module that does rm -v. Since the behaviour is a change from what was happening before it might be nicer to people to default the remove option to false.

**Comment by garethr** [comment]
@hdeadman good idea. I'm working on this now. Adding both `remove_container_on_` and `remove_volume_on_` params.

**Comment by garethr** [comment]
@hdeadman @MichaelMackus I've implemented this and it's in master if you'll like to try out and provide any feedback: https://github.com/garethr/garethr-docker/commit/10a157c80490c9b3df0556a593ce8c7dfc913728

**Comment by hdeadman** [comment]
It looks good and I tried it out. It seems to work. I didn't specify any of the options b/c I like the defaults. 

This isn't a problem with your module but It bothers me that docker doesn't treat named volumes differently that other volumes created by running the container. 
```
docker volume create --name=gitlab-data
docker run -v gitlab-data:/whatever --name gitlab blah/gitlab
docker stop blah/gilab 
docker rm -v blah/gilab   
```
I don't think this should delete my gitlab-data volume that I created with docker volume. If I mapped a container volume to a host directory it wouldn't delete that folder. 

Thanks for the quick fix.

**Comment by MichaelMackus** [comment]
@garethr thanks, but it doesn't seem to be working properly for me... I set all those options to "false", and when I do `/etc/init.d/docker-mycontainer restart` I get the following output:

```bash
Error response from daemon: Conflict. The name "mycontainer" is already in use by container XXXX. You have to remove (or rename) that container to be able to reuse that name.
```

Looking into the init script, it looks like the changes just removed the `docker rm` lines for the container, and just use the `docker run` command to start the container every time. 

Any way we can extend this somehow to check for a running container, and if so start it with `docker start`? Maybe something like this

```bash
if [[ -z $(docker ps -a | grep mycontainer) ]]; then 
    docker start mycontainer
else
   docker run ...
fi
```

Any thoughts?
