### ISSUE TITLE
docker -d is deprecated

### ISSUE THREAD

**Issue by samuelson** [garethr/garethr-docker#427]
On CentOS7 "include docker" fails because the flag "-d" is no longer supported.

The service won't start because of the error.

According to this: https://github.com/docker/docker/blob/master/CHANGELOG.md#180-2015-08-11
The command is now /usr/bin/docker daemon.

Changing the command manually fixed the issue for me.

**Comment by samuelson** [comment]
https://github.com/garethr/garethr-docker/pull/428

**Comment by garethr** [comment]
Merge with a minor change, thanks again @samuelson
