### ISSUE TITLE
daemon_subcommand option needs to be set to something in params.pp?

### ISSUE THREAD

**Issue by hdeadman** [garethr/garethr-docker#430]
I am using the latest version and in params.pp it sets daemon_subcommand_default = 'daemon' but it never sets daemon_subcommand to anything. 

In init.pp it sets   $daemon_subcommand                 = $docker::params::daemon_subcommand,

but $docker::params::daemon_subcommand is undef. 

If it were defaulted to -d then you would at least get an error when upgrading to 1.10 but as it is it just prints out the help. I suppose it should only be -d for older versions of docker but I don't know if you can determine that in params.pp since if someone is specifying an older version of docker they are probably doing it in init.pp.

**Comment by garethr** [comment]
@hdeadman thanks, just fixed in master now. I'm falling forward with this option at the moment. For the release I'll either have a major revision and documentation or fix to allow to work for both without change.
