### ISSUE TITLE
Prefetch docker_network Provider ruby uninitialized constant JSON

### ISSUE THREAD

**Issue by joeljacobs** [garethr/garethr-docker#484]
Adding docker class adds the following line to every puppet run:

Error: Could not prefetch docker_network provider 'ruby': uninitialized constant JSON

Module Version: 5.1.0

**Comment by garethr** [comment]
@joeljacobs thanks. This would appear Ruby environment specific. I've added an explicit require for the json library. That's in master now if you'd like to check it out.
