### ISSUE TITLE
docker --restart=always

### ISSUE THREAD

**Issue by panshul007** [garethr/garethr-docker#494]
How do I configure the docker run with the parameter?

`--restart=always`

`restart_service => true` - states that by default the value is true, but this does not seem to work if the container crashed in last execution due to errors such as `Out of memory`.

**Comment by garethr** [comment]
Their are two ways of doing this, depending on whether you want to use the init scripts or not.

You can pass `extra_parameters` as described here: https://github.com/garethr/garethr-docker/blob/master/manifests/run.pp#L16

```
extra_parameters => ['--restart=always']
```

Or you can pass a value to `restart` directly as mentioned here: https://github.com/garethr/garethr-docker/blob/master/manifests/run.pp#L7

The interface isn't super clear here, and will likely change in a major version in the future.

**Comment by panshul007** [comment]
great thanks... :+1:
