### ISSUE TITLE
Restart policy

### ISSUE THREAD

**Issue by vladgh** [garethr/garethr-docker#505]
`docker::run` validates the restart policies here: https://github.com/garethr/garethr-docker/blob/master/manifests/run.pp#L108

However, there is another policy that is not included: `unless-stopped`

Source: https://docs.docker.com/engine/reference/run/#restart-policies-restart

**Comment by marji** [comment]
I have created PR #586 which adds the "unless-stopped" policy to the validation rule.

**Comment by vladgh** [comment]
Thank you.
