### ISSUE TITLE
Unknown variable: 'docker::params::storage_config' with strict_variables = true

### ISSUE THREAD

**Issue by drscre** [garethr/garethr-docker#508]
I am using garethr/docker version 5.2.0
With strict_variables = true, puppet 4 complains:
```
Unknown variable: 'docker::params::storage_config'. at /vagrant/puppet/environments/production/modules/docker/manifests/init.pp:393:40
```

**Comment by garethr** [comment]
This should now be fixed in master. I'm going to refactor the tests a bit to make sure strict variables are caught for all supported operating systems when I get a chance.
