### ISSUE TITLE
systemd: use RemainAfterExit if detach is true

### ISSUE THREAD

**Issue by alfredkrohmer** [garethr/garethr-docker#511]
When generating service files for systemd, `RemainAfterExit` is never set to true; therefore, if you use `detach => true`, `systemctl status docker-<name>` will display the container as dead and systemd will kill all processes in the scope as a consequence, therefore effectivly stopping the container.

The resolution would be to add `RemainAfterExit=true` only if `detach => true` is set.

**Comment by devkid** [comment]
As an alternative, use `Type=forking` if `detach` is true.

**Comment by devkid** [comment]
Amendment: `Type=forking` does not work, as systemd only monitors the docker client which exits after sending the docker daemon the command to start the container and does not directly spawn the container. Apparently, my initial problem with the containers dying is not really systemd-related, but the problem that `systemctl status` displays the unit as dead still persists, so `RemainAfterExit=true` is a solution at least for this problem.

**Comment by alfredkrohmer** [comment]
Closing since the project seems to be dead
