### ISSUE TITLE
include docker giving error if docker service already running on host

### ISSUE THREAD

**Issue by dvenrao** [garethr/garethr-docker#520]
Error: Could not update: Execution of '/usr/bin/yum -d 0 -e 0 -y install docker-io-1.7.1' returned 1: Error: docker-engine conflicts with docker-io-1.7.1-2.el6.x86_64
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

**Comment by garethr** [comment]
This doesn't appear to be the service but the package. In particular the specific package has an explicit conflict.

What's happening here is that you already have docker from the distro packages. And the module is trying to install docker from the Docker Inc packages. Hence the conflict.

You can either set `manage_package` to false, or alternatively set `use_upstream_package_source = false` if you want to use the distro package. Or you can ensure docker-io is uninstalled (`ensure=>absent`) before installing docker-engine.
