### ISSUE TITLE
docker images specs fails with update_docker_image.sh

### ISSUE THREAD

**Issue by rudgab** [garethr/garethr-docker#537]
Hi,
your update_docker_image.sh uses the json .Config.Image item to proof if a image is pulled out correctly. This Config.Image is only written if you are using the docker import mechanism. I try to build docker images from a dockerfile and then the image name ends up in .ContainerConfig.Image.

May there be a switch to resolve this issue?

Regards,

Rudi G.

**Comment by garethr** [comment]
I had a different issue around the same code and the script now uses Id https://github.com/garethr/garethr-docker/commit/914f3319ae13a6fd7ba642cb7d500a80540b0691. I think that should resolve your problem too but if not please reopen this issue.
