### ISSUE TITLE
Systemd configuration file is not created on Ubuntu 16.04 LTS 

### ISSUE THREAD

**Issue by jyrkiput** [garethr/garethr-docker#541]
I was trying to add label to docker daemon with

    class { 'docker':
      labels => ['testing=true'],
    }

The label did not appear for the daemon. I think that the reason is that the systemd configuration file was not created into /etc/systemd/system/docker.service.d/. Forcing service_overrides_template to the class fixed this:

    class { 'docker':
      labels => ['testing=true'],
      service_overrides_template => 'docker/etc/systemd/system/docker.service.d/service-overrides-debian.conf.erb'
    }

There seems to be related pull request #498 that has test failures, but those failures might be unrelated.

The version of puppet module is 5.2.0

**Comment by garethr** [comment]
I've merged #498 which should resolve this issue. It will be in the next release of the module. Thanks
