### ISSUE TITLE
how to use hiera to define docker version, other params

### ISSUE THREAD

**Issue by obenziane2** [garethr/garethr-docker#594]
does anyone know how to use hiera to define docker version, other params. etc... ?
example: i need to specify: version, tcp_bind, iptables, etc.. ,  as decribed below

class { 'docker':
  tcp_bind        => ['tcp://127.0.0.1:4243','tcp://10.0.0.1:4243'],
  socket_bind     => 'unix:///var/run/docker.sock',
  ip_forward      => true,
  iptables        => true,
  ip_masq         => true,
  bridge          => br0,
  fixed_cidr      => '10.20.1.0/24',
  default_gateway => '10.20.0.1',
}

**Comment by mterzo** [comment]
This should get you started. 

```
docker::tcp_bind: "'tcp://127.0.0.1:2375'"
docker::socket_bind: "unix:///var/run/docker.sock"
docker::version: latest
docker::docker_users:
  - mterzo
```

**Comment by obenziane2** [comment]
awesome, thanks!

**Comment by LongLiveCHIEF** [comment]
@obenziane2 can you close this issue if this answers your question?  Thanks!
