### ISSUE TITLE
proxy regexp isnt quite right

### ISSUE THREAD

**Issue by mjstein** [garethr/garethr-docker#625]
Should be 
^(https?:\/\/)?([\da-z\.-]+)(\.([a-z\.]{2,6}))?(:[\d])?([\/\w \.-]*)*\/?$

in fact I am not entirely sure that (\.([a-z\.]{2,6}) is needed.

**Comment by scotty-c** [comment]
@mjstein Is this issue still valid? or can I close it

**Comment by scotty-c** [comment]
Closing this issue due to no response
