### ISSUE TITLE
When updating docker on Centos to 1.12, docker daemon no longer starts

### ISSUE THREAD

**Issue by jovandeginste** [garethr/garethr-docker#628]
The daemon location has changed (again):
* before 1.10: /usr/bin/docker
* 1.10: /usr/bin/docker-current (but /usr/bin/docker still existed as a shell script)
* 1.12: /usr/bin/dockerd-current

However, the `ExecStart` line of the systemd file has changed dramatically; this is the new value:

```systemd
ExecStart=/usr/bin/dockerd-current \
          --add-runtime docker-runc=/usr/libexec/docker/docker-runc-current \
          --default-runtime=docker-runc \
          --exec-opt native.cgroupdriver=systemd \
          --userland-proxy-path=/usr/libexec/docker/docker-proxy-current \
          $OPTIONS \
          $DOCKER_STORAGE_OPTIONS \
          $DOCKER_NETWORK_OPTIONS \
          $ADD_REGISTRY \
          $BLOCK_REGISTRY \
          $INSECURE_REGISTRY
```

This puppet module writes `/etc/systemd/system/docker.service.d/service-overrides.conf`, which changes the `ExecStart` part.

As a test, I deleted this overrides file on both a 1.10 and 1.12 installation, did a reload of systemd, and everything seems to work so far (daemon starts, containers start, will leave it running over the weekend).

I now changed my puppet profile for docker to this:

```puppet
class {
  '::docker':
    ensure                      => present,
    service_overrides_template  => false,
    [...]
}

file { '/etc/systemd/system/docker.service.d/service-overrides.conf':
  ensure => absent,
}
```

This does not restart the daemon when only deleting the file (which is what I want in that case)

Should the default service-override be updated? Why is it there to begin with?

**Comment by roidelapluie** [comment]
My workaround:

```
  file {
    '/usr/bin/dockerd':
      ensure => link,
      target => '/usr/bin/dockerd-current'
  }
```

**Comment by scotty-c** [comment]
Closing as this has been fixed in later versions of the engine
