### ISSUE TITLE
syntax error at 'unix'; expected ']'

### ISSUE THREAD

**Issue by reveal79** [garethr/garethr-docker#632]
Ubuntu 14.0.4
Puppet version: 3.8.7

/etc/puppet/manifests/site.pp
class { 'docker':
	tcp_bind => ['tcp://192.168.0.100:2375’,’tcp://127.0.0.1:2375’],
	socket_bind => 'unix:///var/run/docker.sock',
}

docker::image { 'ubuntu':
	docker_file => 'puppet:///docker/dockerfile'
 }

running puppet agent -t -d on master results in the following error:
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Could not parse for environment production: Syntax error at 'unix'; expected ']' at /etc/puppet/manifests/site.pp:5 on node test01.testmaster.com

In the puppet forge module repo it shows usage and I am abiding by the usage.

This should run docker and if not install it

**Comment by lazyfrosch** [comment]
This, if at all is an error in your Puppet `site.pp` as suggested by the error:

``` puppet
class { 'docker':
  tcp_bind => ['tcp://192.168.0.100:2375’,’tcp://127.0.0.1:2375’],
  socket_bind => 'unix:///var/run/docker.sock',
}

docker::image { 'ubuntu':
  docker_file => 'puppet:///docker/dockerfile'
}
```

If you copied the original code, only the first single quote `'` is a real quote, you can see that the string ends in the next line from syntax highlighting.

Other quote characters in the tcp_bind line are: http://www.fileformat.info/info/unicode/char/2019/index.htm

You should not copy code from MS-Word (or similar) :wink:

**Comment by reveal79** [comment]
That's weird because I used EOL Unix format when I pasted it in notepad++,
unless I missed that extra quote you provided. I will try your suggestion.

**Comment by gregohardy** [comment]
@lazyfrosch Thanks for sorting that.
