### ISSUE TITLE
Docker Hub login

### ISSUE THREAD

**Issue by lee5i3** [garethr/garethr-docker#657]
Here is the command I'm using

docker::registry { 'https://index.docker.io/v1':
  username => 'myuser',
  password => 'mypassword',
}

I am getting the following error "Notice: /Stage[main]/Main/Node[default]/Docker::Registry[https://index.docker.io/v1]/Exec[https://index.docker.io/v1 auth]/returns: Error: Cannot perform an interactive login from a non TTY device"

How can I have puppet log into docker hub?

**Comment by fgabriel78** [comment]
I have exactly the same problem. It is a recent problems, some weeks ago it worked perfectly.
¿Maybe any changes in the Docker auth system?

**Comment by ghost** [comment]
I ran into this as well. The code for release 5.3.0 doesn't have email as being optional. So you must supply an email

```
docker::registry { 'https://index.docker.io/v1':
username => 'myuser',
password => 'mypassword',
email => 'my@email.com'
}
```

Then it will work. If you have the code straight from the github repo then the email is optional.
