### ISSUE TITLE
Docker compose v3 not supported

### ISSUE THREAD

**Issue by joaquin386** [garethr/garethr-docker#665]
Hi

I just wanted to use a couple of the features the v3 docker compose provies but when running at the beginning of the file:

version: "3"

It says:
Error: Could not evaluate: Unsupported docker compose file syntax version "3"!

Thanks

**Comment by joaquin386** [comment]
vi lib/puppet/provider/docker_compose/ruby.rb

Change:
  when /^2(\.0)?$/
to:
  when /^3(\.0)?$/

Solved the issue. I suppose as well adding the whole loop would be better. Might do a clone, push

**Comment by dbason** [comment]
@joaquin386 you're better off changing it to
```
when /^[2-3](.0)?$/
```

This way you don't break compatibility

**Comment by joaquin386** [comment]
@dbason check this PR --> https://github.com/garethr/garethr-docker/pull/666
I left the one with 2 (for backwards compatible) and added 3 and 3.1
Still need to re-amend the PR (just on vacation currently)
