### ISSUE TITLE
Use the new "edge" and "stable" repositories

### ISSUE THREAD

**Issue by vide** [garethr/garethr-docker#688]
Since Docker Inc has changed its release cycle, they now have an "edge" channel, with monthly releases, and a "stable" channel, with releases every 4 months. Right now the repo configured by this module, at least, in CentOS, only configure the "edge" channel (I think because it's a remap of the old unique distribution channel). Here are the instructions on how to install them.

https://store.docker.com/editions/community/docker-ce-server-centos
https://store.docker.com/editions/community/docker-ce-server-debian
https://store.docker.com/editions/community/docker-ce-server-ubuntu

Are you going to accept a PR on this topic? I don't want to spend time on it if it's going to be ignored. Thanks!

**Comment by stefanlasiewski** [comment]
Also see #676

**Comment by vide** [comment]
@stefanlasiewski you're totally right, didn't see your issue before.Closing mine as duplicated :)
