### ISSUE TITLE
Additional groups does not work, CentOS 6.9, docker v1.7.1

### ISSUE THREAD

**Issue by mmarseglia** [garethr/garethr-docker#706]
On CentOS 6.9, docker 1.7.1, adding additional users to use docker does not work.

Puppet creates the group 'dockerroot' but on CentOS 6.9 the group should be 'docker'.

Just wanted to raise this before I dig into it.  Have others have experienced the same thing or can someone also reproduce?

**Comment by Justin-DynamicD** [comment]
maybe, as you're on an older version, this is a non-issue but ... according to docker documentation CentOS 6.x isn't supported at all,  You have to be >7:

https://docs.docker.com/engine/installation/linux/docker-ce/centos/

```To install Docker CE, you need the 64-bit version of CentOS 7.```

I only know this as I just recently rewrote my classes to avoid accidentally installing on my 6.9 boxes.

**Comment by mmarseglia** [comment]
Thanks!  I didn't know about the centos 7 requirement.  I'll close this out since docker's doc states that.
