### ISSUE TITLE
Amazon Linux 2 support

### ISSUE THREAD

**Issue by alfredkrohmer** [garethr/garethr-docker#744]
Amazon Linux 2 reports
```bash
$ facter operatingsystem
Amazon
$ facter operatingsystemrelease
2.0
```

This breaks this puppet module with this error:
https://github.com/garethr/garethr-docker/blob/master/manifests/install.pp#L42

Also, it still tries to generate init scripts instead of systemd unit files (systemd is now used with Amazon Linux 2).

**Comment by alfredkrohmer** [comment]
Closing since the project seems to be dead

**Comment by RussellMcOrmond** [comment]
I wish this repo was updated to point to the maintained fork at https://github.com/puppetlabs/puppetlabs-docker
