### ISSUE TITLE
Add service_provider parameter to docker class.

### ISSUE THREAD

**Issue by mtbvang** [garethr/garethr-docker#91]
I'm hitting the issues mentioned in the following post and it seems that the only work around at the moment is to add a service_provider parameter to the docker class to enable it to be settable. I'm happy to make the changes and do pull request if you think that is a good idea.

 http://ask.puppetlabs.com/question/13635/how-to-use-puppet-modules-that-require-upstart-with-docker/

Docker containers don't really support the puppet upstart service provider and the only work around I know of at the moment is to set provider=base. Seems like a good idea to expose the provider as a parameter anyway.

**Comment by garethr** [comment]
Hi @mtbvang. First up, apologies for not reply to this much sooner. I'm just going through triaging all the issues. The module does now support passing a provider directly - https://github.com/garethr/garethr-docker/blob/master/manifests/init.pp#L300. Thanks.
