### ISSUE TITLE
pull latest container

### ISSUE THREAD

**Issue by hackzilla** [garethr/garethr-docker#93]
I'm trying to figure out the best way to upgrade the docker containers using puppet.

Currently trying:
```
	docker::image { 'kohana-remove':
	  ensure  => 'absent',
	  image   => 'docker.ukwm.local:5000/ukwm/container',
	  require => Class['ukwm::packages::docker'],
	}
    ->
	docker::image { 'kohana-install':
	  ensure  => 'latest',
	  image   => 'docker.ukwm.local:5000/ukwm/container',
	  require => Class['ukwm::packages::docker'],
	}
    ->
	docker::run { 'kohana':
	  image           => 'docker.ukwm.local:5000/ukwm/container',
	  ports           => ['81:80', '2221:22'],
	  use_name        => true,
	  restart_service => true,
	  privileged      => false,
	}
```

Which outputs:
```
Error: docker rmi docker.ukwm.local:5000/ukwm/container returned 1 instead of one of [0]
Error: /Stage[main]/Stats::Backend::Kohana/Docker::Image[kohana-remove]/Exec[docker rmi docker.ukwm.local:5000/ukwm/container]/returns: change from notrun to 0 failed: docker rmi docker.ukwm.local:5000/ukwm/container returned 1 instead of one of [0]
Warning: /Stage[main]/Ukwm::Backend::Kohana/Docker::Image[kohana-install]/Exec[docker pull docker.ukwm.local:5000/ukwm/stats-kohana]: Skipping because of failed dependencies
Warning: /Stage[main]/Ukwm::Backend::Kohana/Docker::Run[kohana]/File[/etc/init/docker-kohana.conf]: Skipping because of failed dependencies
Warning: /Stage[main]/Ukwm::Backend::Kohana/Docker::Run[kohana]/Service[docker-kohana]: Skipping because of failed dependencies
```

So maybe an option of force ```docker rm -f <container>```

What would be nicer, is if could notify run that the image has been update. Then it could stop, remove, and restart container.

This would be the command I'd use.
```
	docker::image { 'kohana-install':
	  ensure  => 'latest',
	  image   => 'docker.ukwm.local:5000/ukwm/container',
	  require => Class['ukwm::packages::docker'],
	}

	docker::run { 'kohana':
	  image           => 'docker.ukwm.local:5000/ukwm/container',
	  ports           => ['81:80', '2221:22'],
	  use_name        => true,
	  restart_service => true,
	  privileged      => false,
	}
```

```docker run --rm``` could be added to accomplish some of that.

**Comment by bchecketts** [comment]
Not a complete puppet-based solution, but my PR at https://github.com/garethr/garethr-docker/pull/209 provides a way to stop and restart the container with the newest image via the init script on the machine.

You'd simply run /etc/init.d/docker-YOURNAME cleanRestart

That will stop the container, remove the file in /var/run/docker-YOURNAME.cid, then restart the container with a fresh 'docker pull'.     Note that you could 'docker pull' before running the init command to speed that up so that the current image is already on the machine.

**Comment by garethr** [comment]
After much back and forth and great work by @solarkennedy this should now be resolved. Thanks all https://github.com/garethr/garethr-docker/pull/222/files
